<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>VAdvantage</RootNamespace>
    <AssemblyName>VAWorkflow</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);NU1701;CS0618;SYSLIB0;SYSLIB0011;CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreLibrary\CoreLibrary.csproj" />
    <ProjectReference Include="..\BaseLibrary\BaseLibrary.csproj" />
    <ProjectReference Include="..\XModel\XModel.csproj" />
    <ProjectReference Include="..\VAModelAD\VAModelAD.Core.csproj" />
    <ProjectReference Include="..\ModelLibrary\ModelLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

</Project>
